#ifndef CONSTANT_H
#define CONSTANT_H

#define APPEND_ENTRIES_RPC_LENGTH		1024
#define REQUEST_VOTE_RPC_LENGTH			2048
#define RESPONSE_APPEND_ENTRIES_LENGTH	16
#define RESPONSE_REQUEST_VOTE_LENGTH	16
#define ENTRIES_STR_LENGTH				1024
#define ENTRY_STR_LENGTH				32
#define COMMAND_STR_LENGTH				22

#endif //CONSTANT_H
